title: "Metodología de la Investigación en Educación Infantil"
description: "Libro web docente para el Grado en Educación Infantil"

url: "https://samigabacho.github.io"
baseurl: "/metodologia-investigacion-educacion-infantil"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

nav_enabled: true
search_enabled: true
heading_anchors: true
